# Generated by Django 5.2 on 2025-04-27 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('continent', models.CharField(choices=[('AF', 'Africa'), ('AS', 'Asia'), ('EU', 'Europe'), ('NA', 'North America'), ('SA', 'South America'), ('OC', 'Oceania'), ('AN', 'Antarctica')], max_length=2)),
                ('description', models.TextField()),
                ('highlights', models.TextField()),
                ('best_time_to_visit', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='destinations/')),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='activities/')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='destinations.destination')),
            ],
            options={
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('hotel', 'Hotel'), ('resort', 'Resort'), ('hostel', 'Hostel'), ('apartment', 'Apartment'), ('villa', 'Villa'), ('guesthouse', 'Guesthouse')], max_length=20)),
                ('description', models.TextField()),
                ('amenities', models.TextField()),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='accommodations/')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to='destinations.destination')),
            ],
        ),
    ]
